<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLr3ttqq\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLr3ttqq/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerLr3ttqq.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerLr3ttqq\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerLr3ttqq\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Lr3ttqq',
    'container.build_id' => 'ed9e86ee',
    'container.build_time' => 1522760122,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerLr3ttqq');
